# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-11 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='props',
            name='created_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
