# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-30 20:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0002_auto_20170911_1041'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_date', models.DateField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='detector.Comment')),
                ('prop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detector.Props')),
            ],
        ),
    ]
