# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-05 16:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0002_auto_20170911_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='props',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='searcher.Article'),
        ),
        migrations.DeleteModel(
            name='Article',
        ),
    ]
