# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-07 16:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0004_auto_20180607_1021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='props',
            old_name='proposition',
            new_name='propaganda',
        ),
        migrations.AlterField(
            model_name='comment',
            name='prop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='detector.Props'),
        ),
    ]
